// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using triaCSharp.Data;

namespace triaCSharp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriaCSharp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "josé",
                            ProdutoId = 1,
                            company = "coca",
                            createdAt = new DateTime(2021, 3, 8, 12, 2, 17, 578, DateTimeKind.Local).AddTicks(1965),
                            mail = "a@asdas.com",
                            notes = "jsahdausi",
                            phone = "12121-2121",
                            updatedAt = new DateTime(2021, 3, 8, 12, 2, 17, 579, DateTimeKind.Local).AddTicks(875)
                        },
                        new
                        {
                            Id = 2,
                            Name = "josé2",
                            ProdutoId = 1,
                            company = "coca",
                            createdAt = new DateTime(2021, 3, 8, 12, 2, 17, 579, DateTimeKind.Local).AddTicks(3641),
                            mail = "a@asdas.com",
                            notes = "jsahdausi",
                            phone = "12121-2121",
                            updatedAt = new DateTime(2021, 3, 8, 12, 2, 17, 579, DateTimeKind.Local).AddTicks(3646)
                        });
                });

            modelBuilder.Entity("TriaCSharp.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Desenvolvimento de App"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desenvolvimento Web"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Integração com SAP"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Integração com Mastersaf"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Suporte Nível Especialista"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Solução Tributária"
                        });
                });

            modelBuilder.Entity("TriaCSharp.Models.Cliente", b =>
                {
                    b.HasOne("TriaCSharp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
